name: Run Calendar Check Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Run daily at 01:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests msal pytz

      - name: Run calendar check script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: python scripts/check_calendar.py
